project:
  type: website

website:
  title: "Middleton Lab"
  favicon: favico.ico
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "People"
        file: people.qmd
      - text: "Research"
        file: research.qmd
      - text: "News"
        file: news.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "Software"
        file: software.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Values"
        file: ride.qmd
        

format:
  html:
    theme: simplex
    fontsize: 1.1em
    linestretch: 1.7
    css: styles.css
    toc: true



