project:
  type: website

website:
  title: "Middleton Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: news.qmd
        text: News
      - href: teaching.qmd
        text: Teaching
      - href: software.qmd
        text: Software

format:
  html:
    theme: simplex
    fontsize: 1.1em
    linestretch: 1.7
    css: stles.css
    toc: true



