project:
  type: website

website:
  title: "Middleton Lab"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - sidebar:projects
      - href: people.qmd
        text: "People"
      - href: publications.qmd
        text: "Publications"
      - href: news.qmd
        text: "News"
      - href: teaching.qmd
        text: "Teaching"
      - href: software.qmd
        text: "Software"

  sidebar:
    - id: projects
      title: "Projects"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - mice.qmd

format:
  html:
    theme: simplex
    fontsize: 1.1em
    linestretch: 1.7
    css: styles.css
    toc: true



