---
title: "R.I.D.E."
---

*I would like to acknowledge that I work in what is colonially known as "Missouri," and that these were the homelands of the tribal nations of the Nutachi (Missouria), Jiwere (Otoe), Wahzhazhe (Osage), Ogáxpa (Quapaw), Chikasha (Chickasaw), Illini, and Báxoǰe (Ioway), among others.*

Four core values of our lab are respect, inclusion, diversity, and equality.

## Respect

We expect lab members to contribute to a friendly and thus productive environment which promotes personal growth, learning, and research. We expect that everyone will treat their colleagues with respect, listen to others’ viewpoints and ideas, and ensure the lab is a place where everybody feels welcome and appreciated. Racist, sexist, or other inappropriate comments or behavior will not be tolerated under any circumstance.


## Inclusion

We believe that everyone has a place in biology regardless of race, gender, sexual orientation, gender identity, ethnicity, socioeconomic status, nationality , age, religious affiliation, physical abilities, learning disabilities, family and parental status, and veteran status.


## Diversity

We believe that strength comes from diversity. All individual uniqueness provides opportunity for learning and growth. We commit to supporting each other in promoting a more diverse community of science.


## Equality

We believe in equal participation of all groups and that we should actively work against policies and procedures that have systematically excluded and marginalized groups. We take an anti-oppression and anti-racist mindset and will actively counter oppression at all levels. 
